-- CreateTable
CREATE TABLE "Flee" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "catId" INTEGER,
    "dogId" INTEGER,
    CONSTRAINT "Flee_catId_fkey" FOREIGN KEY ("catId") REFERENCES "Cat" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Flee_dogId_fkey" FOREIGN KEY ("dogId") REFERENCES "Dog" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
